a20davidvg.kozow.com/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ArchivoController;
use App\Http\Controllers\ClienteController;
use App\Http\Controllers\RegistroController;

use App\Http\Controllers\ArchivoInvitadosController;
use App\Http\Controllers\ClienteInvitadosController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get("hola", function(){
    return "Esto é unha proba";
});

Route::get("hola/{usuario}", function($usuario){
    return "Esto é unha proba $usuario";
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource("registro", RegistroController::class);




Auth::routes();


Route::resource('users', UserController::class)->middleware("auth");

Route::resource('clientes/invitado', ClienteInvitadosController::class);

Route::resource('clientes', ClienteController::class)->middleware("auth");
Route::get('clientestelegram', [App\Http\Controllers\ClienteInvitadosController::class, 'clientestelegram'])->name('clientes.clientestelegram');
Route::get('clientespdf', [App\Http\Controllers\ClienteInvitadosController::class, 'clientespdf'])->name('clientes.clientespdf');

Route::resource('archivos/invitados', ArchivoInvitadosController::class);

Route::resource('archivos', ArchivoController::class);
Route::post("/download", [ArchivoController::class, "download"])->name('archivos.download');

Route::get('archivostelegram', [App\Http\Controllers\ArchivoController::class, 'archivostelegram'])->name('archivos.archivostelegram');


Route::resource('archivos/{id}', ArchivoController::class)->middleware("auth");

a20davidvg.kozow.com/app/Models/Archivo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Archivo extends Model
{
    use HasFactory;

    protected $fillable = [
        'id',
        'titulo',
        'enlace',
        'descripcion',
        'cliente_id'
    
    ];


}

a20davidvg.kozow.com/app/Http/Controllers/ArchivoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Archivo;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\DB;
use App\Http\Requests\StoreArchivo;
use Illuminate\Support\Facades\Storage;
use Barryvdh\DomPDF\PDF;

class ArchivoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
       // Para mostrar resultados archivos:
       $archivos = Archivo::paginate(); 

       return view('archivos.index')->with('archivos', $archivos);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($user_id)
    {
        return view("archivos.create")->with("user_id", $user_id);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreArchivo $request)
    {
        $datosvalidados = $request->validated();

      

        $zipA = $request->file("enlace")->store("files");

        

        $datosvalidados["enlace"] = $zipA;

        Archivo::create($datosvalidados);
        
        
       


        // Guarde un mensaje Flash.

        return redirect()->route('clientes.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
    
  
        
       $archivos = DB::table("archivos")->where("cliente_id", $id)->get();
        if (! $archivos)
		{
			// Se devuelve un array errors con los errores detectados y código 404
			return response()->json(['errors'=>Array(['code'=>404,'message'=>'No se encuentra el archivo con ese id.'])],404);
		}

		return view('archivos.id')->with('archivos', $archivos)->with("id", $id); 
    
      
	
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('archivos.edit')->with("id",$id);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreArchivo $request, $id)
    {

        $archivos = $request->validated();

        

            $enlace = DB::table("archivos")->where("id", $id)->select("enlace")->get();


            Storage::delete($enlace[0]->enlace);

            $zipA = $request->file("enlace")->store("files");

            $datosvalidados["enlace"] = $zipA;
            DB::table("archivos")->where("id", $id)->update(["titulo"=> $archivos["titulo"]], ["descripcion"=>$archivos["descripcion"]], ["enalce"=>$archivos["enlace"]]);
   
        
         
         return redirect()->route('clientes.index');
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Archivo $archivo)
    {   
        Storage::delete($archivo["enlace"]);
        $archivo->delete();
        return redirect()->route('clientes.index');
    }


    public function download(Request $request){
        $ids = [];
        $data = $request->except('_token');
foreach($data as $id => $value){
    array_push($ids, $id);
}
        $enlc = $ids[1];

        $pos = strlen($enlc)-4;

        $enlc[$pos]=".";

        

        return Storage::download($enlc);

    }

    public function archivosTelegram()
    {
        
       // Para mostrar resultados archivos:
       $archivos = Archivo::paginate(); 

       

       return response()->json($archivos);

    }


}

a20davidvg.kozow.com/resources/views/archivos/create.blade.php
@extends('plantillas.master')



@section('central')

<center><h2>CREACIÓN DE ARCHIVO</h2></center>


                <div class="card-header">CREACIÓN</div>



    <form action="{{route('archivos.store')}}"  method="post" id="myForm" enctype="multipart/form-data"> 
        @csrf
        <div class="row mb-3">
        
            <center><label for="cliente_id">ID Usuario:</label></center>
            
            <select class= "form-select" name="cliente_id" id="cliente_id">
                <option value="{{$user_id}}" selected="true">{{$user_id}}</option>
            </select>
        
        </div>
        
@include('archivos.form')

    </form>

            
      
</div>
@stop

a20davidvg.kozow.com/resources/views/archivos/edit.blade.php
@extends('plantillas.master')

@section('central')

<center><h2>EDICIÓN DE ARCHIVO</h2></center>

<div class="container">
    <form action="{{route('archivos.update', $id)}}" method="post" id = "myForm" enctype="multipart/form-data"> 
        
        @csrf
        @method('PATCH')
      
        
@include('archivos.form')

    </form>
</div>
@stop

a20davidvg.kozow.com/resources/views/archivos/form.blade.php
 <div class="row mb-3">
    <label class="col-md-4 col-form-label text-md-end"for="nombre">Titulo:</label>
    <div class="col-md-6">
    <input type="text" class="form-control" name="titulo" id="titulo">
    @error("titulo")
        <small class="text-danger">{{$message}}</small>
    @enderror
    </div>
 </div>
 <div class="row mb-3">
        <label class =" col-md-4 col-form-label text-md-end"for="exampleFormControlTextarea1">Descripción</label>
        <div class="col-md-6">
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" form="myForm" name="descripcion"></textarea>
      
 
    @error("descripcion")
        <small class="text-danger">{{$message}}</small>
    @enderror
 </div>
 </div>
    <div class="row mb-3">
        <label class="col-md-4 col-form-label text-md-end" for="enlace">Enlace:</label>
        <div class="col-md-6">
        <input type="file" class="form-control" name="enlace" id="enlace">
        @error("enlace")
            <small class="text-danger">{{$message}}</small>
        @enderror
        </div>    
    </div>



    </div>
   <center> <input type="submit" class= "btn btn-success" name="enviar"></center>
    
    
    

a20davidvg.kozow.com/resources/views/archivos/id.blade.php
@extends('plantillas.master')



@section('central')
<h2>LISTADO DE ARCHIVOS</h2><a href="{{ route('{id}.create', $id) }}" class="btn btn-primary">Crear <i class="fa fa-plus-square"></i></a>

<table class="table">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">UserID</th>
            <th scope="col">Titulo</th>
            <th scope="col">Enlace</th>
            <th scope="col">Descripción</th>
            <th scope="col">Fecha Creación</th>
            
        </tr>
    </thead>
    <tbody>
        @foreach($archivos as $archivo)
        <tr>
            <th scope="row">{{ $archivo->id }}</th>
            <th scope="row">{{ $archivo->cliente_id }}</th>
            <th scope="row">{{ $archivo->titulo}}</th>
            <th scope="row">{{ $archivo->enlace }}</th>
            <th scope="row">{{ $archivo->descripcion }}</th>
            <th scope="row">{{ $archivo->created_at }}</th>
            <th scope="row"><a href="{{ route('archivos.edit', $archivo->id) }}" class="btn btn-outline-success">Editar</a>
         <form action="{{route('archivos.destroy', $archivo->id)}}" method="post">@csrf @method('DELETE') <input type="submit" class=" btn btn-outline-danger" value="Borrar" /></form> <form action="{{route('archivos.download', $archivo->enlace)}}" method="post">@csrf @method('POST') <button type="submit" class="btn btn-outline-primary" value="{{ $archivo->enlace }}"><i class="fa fa-download"></i></button></form>
            </th>
        </tr>

        @endforeach
    </tbody>

</table>





@stop

a20davidvg.kozow.com/resources/views/archivos/idInvitados.blade.php
@extends('plantillas.master')



@section('central')
<h2>LISTADO DE ARCHIVOS</h2>

<table class="table">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">UserID</th>
            <th scope="col">Titulo</th>
            <th scope="col">Enlace</th>
            <th scope="col">Descripción</th>
            <th scope="col">Fecha Creación</th>
            
        </tr>
    </thead>
    <tbody>
        @foreach($archivos as $archivo)
        <tr>
            <th scope="row">{{ $archivo->id }}</th>
            <th scope="row">{{ $archivo->cliente_id }}</th>
            <th scope="row">{{ $archivo->titulo}}</th>
            <th scope="row">{{ $archivo->enlace }}</th>
            <th scope="row">{{ $archivo->descripcion }}</th>
            <th scope="row">{{ $archivo->created_at }}</th>
            <th scope="row"> <form action="{{route('archivos.download', $archivo->enlace)}}" method="post">@csrf @method('POST') <button type="submit" class="btn btn-outline-primary" value="{{ $archivo->enlace }}"><i class="fa fa-download"></i></button></form>
            </th>
        </tr>

        @endforeach
    </tbody>

</table>





@stop

a20davidvg.kozow.com/resources/views/archivos/index.blade.php
@extends('plantillas.master')



@section('central')
<h2>LISTADO DE ARCHIVOS</h2>
<table class="table">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">UserID</th>
            <th scope="col">Titulo</th>
            <th scope="col">Enlace</th>
            <th scope="col">Descripción</th>
            <th scope="col">Fecha Creación</th>
            <th scope="col">Descarga</th>
            
        </tr>
    </thead>
    <tbody>
        @foreach($archivos as $archivo)
        <tr>
            <th scope="row">{{ $archivo->id }}</th>
            <th scope="row">{{ $archivo->cliente_id }}</th>
            <th scope="row">{{ $archivo->titulo}}</th>
            <th scope="row">{{ $archivo->enlace }}</th>
            <th scope="row">{{ $archivo->descripcion }}</th>
            <th scope="row">{{ $archivo->created_at }}</th>
            <th><form action="{{route('archivos.download', $archivo->enlace)}}" method="post">@csrf @method('POST') <button type="submit" class="btn btn-outline-primary" value="{{ $archivo->enlace }}"><i class="fa fa-download"></i></button></form></th>
        </tr>
        @endforeach
    </tbody>
</table>

{!! $archivos->links() !!}

@stop

a20davidvg.kozow.com/resources/views/archivos/usuario.blade.php
@extends('plantillas.master')



@section('central')
<h2>LISTADO DE ARCHIVOS</h2>
<table class="table">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">UserID</th>
            <th scope="col">Titulo</th>
            <th scope="col">Enlace</th>
            <th scope="col">Descripción</th>
            <th scope="col">Fecha Creación</th>
            <th scope="col">Descargar</th>
            
        </tr>
    </thead>
    <tbody>
        @foreach($archivos as $archivo)
        <tr>
            <th scope="row">{{ $archivo->id }}</th>
            <th scope="row">{{ $archivo->cliente_id }}</th>
            <th scope="row">{{ $archivo->titulo}}</th>
            <th scope="row">{{ $archivo->enlace }}</th>
            <th scope="row">{{ $archivo->descripcion }}</th>
            <th scope="row">{{ $archivo->created_at }}</th>
            <th><form action="{{route('archivos.download', $archivo->enlace)}}" method="post">@csrf @method('POST') <button type="submit" class="btn btn-outline-primary" value="{{ $archivo->enlace }}"><i class="fa fa-download"></i></button></form></th>
        </tr>
        @endforeach
    </tbody>
</table>



@stop