a20davidvg.kozow.com/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ArchivoController;
use App\Http\Controllers\ClienteController;
use App\Http\Controllers\RegistroController;

use App\Http\Controllers\ArchivoInvitadosController;
use App\Http\Controllers\ClienteInvitadosController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get("hola", function(){
    return "Esto é unha proba";
});

Route::get("hola/{usuario}", function($usuario){
    return "Esto é unha proba $usuario";
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource("registro", RegistroController::class);




Auth::routes();


Route::resource('users', UserController::class)->middleware("auth");

Route::resource('clientes/invitado', ClienteInvitadosController::class);

Route::resource('clientes', ClienteController::class)->middleware("auth");
Route::get('clientestelegram', [App\Http\Controllers\ClienteInvitadosController::class, 'clientestelegram'])->name('clientes.clientestelegram');
Route::get('clientespdf', [App\Http\Controllers\ClienteInvitadosController::class, 'clientespdf'])->name('clientes.clientespdf');

Route::resource('archivos/invitados', ArchivoInvitadosController::class);

Route::resource('archivos', ArchivoController::class);
Route::post("/download", [ArchivoController::class, "download"])->name('archivos.download');

Route::get('archivostelegram', [App\Http\Controllers\ArchivoController::class, 'archivostelegram'])->name('archivos.archivostelegram');


Route::resource('archivos/{id}', ArchivoController::class)->middleware("auth");

a20davidvg.kozow.com/app/Models/Cliente.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Cliente extends Model
{
    use HasFactory;

    protected $fillable = [
        'id',
        'nombre',
        'apellidos',
        'email',
        'telefono',
        'usuario',
        'password',

    ];

      /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];



    public function archivos()
    {
        return $this->hasMany(Archivo::class);
    }

}

a20davidvg.kozow.com/app/Http/Controllers/ClienteController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Cliente;
use Illuminate\Http\Request;
use App\Http\Requests\StoreUser;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use Illuminate\Contracts\Session\Session;

class ClienteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
         // Conseguir todos los eventos
       $clientes = Cliente::all();
       // Para mostrar resultados paginados:
       $clientes = Cliente::paginate(10);    
       return view('clientes.index')->with('clientes', $clientes);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("clientes.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUser $request)
    {
        $datosvalidados = $request->validated();

        User::create($datosvalidados);

        // Guarde un mensaje Flash.

        return redirect()->route('clientes.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $cliente = DB::table("clientes")->where("id", $id)->get();
        if (! $cliente)
		{
			// Se devuelve un array errors con los errores detectados y código 404
			return response()->json(['errors'=>Array(['code'=>404,'message'=>'No se encuentra el archivo con ese id.'])],404);
		}

		return view('clientes.id')->with('clientes', $cliente); 
    
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Cliente $cliente)
    {
        return view('clientes.edit')->with('cliente', $cliente);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreUser $request, Cliente $cliente)
    {
        $cliente->update($request->validated());
        return redirect()->route('clientes.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Cliente $cliente)
    {
        $cliente->delete();

        // Guarde un mensaje Flash.
      

        // Redireccionamos al index.
        return redirect()->route('clientes.index');
    }
}

a20davidvg.kozow.com/resources/views/clientes/create.blade.php
@extends('plantillas.master')



@section('central')

<h2>CREACIÓN DE CLIENTE</h2>

<div class="container md-3">
    <form action="{{route('clientes.store')}}" method="post"> 
        @csrf
@include('clientes.form')

    </form>
@stop

a20davidvg.kozow.com/resources/views/clientes/edit.blade.php
@extends('plantillas.master')



@section('central')

<center><h2>EDICIÓN DE CLIENTE</h2></center>

<div class="container ">
    <form action="{{route('clientes.update',$cliente->id)}}" method="post"> 
        @csrf
        @method('PUT')
@include('clientes.form')

    </form>
</div>
@stop

a20davidvg.kozow.com/resources/views/clientes/form.blade.php
<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">Formulario</div>

            <div class="card-body">
                <form method="POST" action="{{ route('register') }}">
                    @csrf

                    <div class="row mb-3">
                        <label for="nombre" class="col-md-4 col-form-label text-md-end">{{ __('Nombre') }}</label>

                        <div class="col-md-6">
                            <input id="nombre" type="text" class="form-control @error('nombre') is-invalid @enderror" name="nombre" value="{{ old('name') }}" required autocomplete="nombre" autofocus>

                            @error('nombre')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label for="apellidos" class="col-md-4 col-form-label text-md-end">{{ __('Apellidos') }}</label>

                        <div class="col-md-6">
                            <input id="apellidos" type="text" class="form-control @error('apellidos') is-invalid @enderror" name="apellidos" value="{{ old('apellidos') }}" required autocomplete="apellidos" autofocus>

                            @error('apellidos')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label for="usuario" class="col-md-4 col-form-label text-md-end">{{ __('Usuario') }}</label>

                        <div class="col-md-6">
                            <input id="usuario" type="text" class="form-control @error('usuario') is-invalid @enderror" name="usuario" value="{{ old('usuario') }}" required autocomplete="usuario" autofocus>

                            @error('usuario')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label for="email" class="col-md-4 col-form-label text-md-end">{{ __('Email') }}</label>

                        <div class="col-md-6">
                            <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email">

                            @error('email')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label for="telefono" class="col-md-4 col-form-label text-md-end">{{ __('Telefono') }}</label>

                        <div class="col-md-6">
                            <input id="telefono" type="text" class="form-control @error('telefono') is-invalid @enderror" name="telefono" value="{{ old('telefono') }}" required autocomplete="telefono" autofocus>

                            @error('telefono')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    

                    <div class="row mb-3">
                        <label for="password" class="col-md-4 col-form-label text-md-end">{{ __('Contraseña') }}</label>

                        <div class="col-md-6">
                            <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="new-password">

                            @error('password')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label for="password-confirm" class="col-md-4 col-form-label text-md-end">{{ __('Confirma contraseña') }}</label>

                        <div class="col-md-6">
                            <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password">
                        </div>
                    </div>
                    <center>
                    <div class="row mb-0">
                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                {{ __('Crear/Editar cliente') }}
                            </button>
                        </div>

                    </div>
                    </center>
                </form>
            </div>
        </div>
    </div>
</div>
</div>

a20davidvg.kozow.com/resources/views/clientes/id.blade.php
@extends('plantillas.master')



@section('central')
<h2>Usuario:</h2>
<table class="table">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Nombre</th>
            <th scope="col">Apellidos</th>
            <th scope="col">Email</th>
            <th scope="col">Teléfono</th>
            
        </tr>
    </thead>
    <tbody>
        @foreach($users as $user)
        <tr>
            <th scope="row">{{ $user->id }}</th>
            
            <th scope="row">{{ $user->nombre}}</th>
            <th scope="row">{{ $user->apellidos }}</th>
            <th scope="row">{{ $user->email }}</th>
            <th scope="row">{{ $user->telefono }}</th>
        </tr>
        @endforeach
    </tbody>
</table>



@stop

a20davidvg.kozow.com/resources/views/clientes/index.blade.php
@extends('plantillas.master')

@section('title')

@stop

@section('central')
<h2>LISTADO DE CLIENTES</h2>
<table class="table">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Usuario</th>
            <th scope="col">Nombre</th>
            <th scope="col">Apellidos</th>
            <th scope="col">Email</th>
            <th scope="col">Teléfono</th>
            
        </tr>
    </thead>
    <tbody>
        @foreach($clientes as $cliente)
        <tr>
            <th scope="row">{{ $cliente->id }}</th>
            <th scope="row">{{ $cliente->usuario }}</th>
            <th scope="row">{{ $cliente->nombre}}</th>
            <th scope="row">{{ $cliente->apellidos }}</th>
            <th scope="row">{{ $cliente->email }}</th>
            <th scope="row">{{ $cliente->telefono }}</th>
            <th scope="row"><a href="{{ route('clientes.edit',$cliente) }}" class="btn btn-outline-primary">Editar</a>
            <form action="{{ route('clientes.destroy',$cliente) }}" method="post">@csrf @method('DELETE') <input type="submit" class="btn btn-outline-danger" value="Borrar" /></form> <a href="{{ route('archivos.show', $cliente ) }}" class="btn btn-outline-secondary">Archivos</a>
        </tr>
        @endforeach
    </tbody>
</table>



@stop

a20davidvg.kozow.com/resources/views/clientes/indexInvitados.blade.php
@extends('plantillas.master')

@section('title')

@stop

@section('central')
<h2>LISTADO DE USUARIOS</h2>
<table class="table">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Usuario</th>
            <th scope="col">Nombre</th>
            <th scope="col">Apellidos</th>
            <th scope="col">Email</th>
            <th scope="col">Teléfono</th>
            
        </tr>
    </thead>
    <tbody>
        @foreach($clientes as $cliente)
        <tr>
            <th scope="row">{{ $cliente->id }}</th>
            <th scope="row">{{ $cliente->usuario }}</th>
            <th scope="row">{{ $cliente->nombre}}</th>
            <th scope="row">{{ $cliente->apellidos }}</th>
            <th scope="row">{{ $cliente->email }}</th>
            <th scope="row">{{ $cliente->telefono }}</th>
            <th scope="row"> <a href="{{ route('invitados.show', $cliente ) }}" class="btn btn-outline-primary">Archivos</a></th>
        </tr>
        @endforeach
    </tbody>
</table>


@stop

a20davidvg.kozow.com/resources/views/clientes/pdfclientes.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<h2>LISTADO DE USUARIOS</h2>
<table class="table">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Usuario</th>
            <th scope="col">Nombre</th>
            <th scope="col">Apellidos</th>
            <th scope="col">Email</th>
            <th scope="col">Teléfono</th>
            
        </tr>
    </thead>
    <tbody>
        @foreach($clientes as $cliente)
        <tr>
            <th scope="row">{{ $cliente["id"] }}</th>
            <th scope="row">{{ $cliente["usuario"] }}</th>
            <th scope="row">{{ $cliente["nombre"]}}</th>
            <th scope="row">{{ $cliente["apellidos"] }}</th>
            <th scope="row">{{ $cliente["email"] }}</th>
            <th scope="row">{{ $cliente["telefono"] }}</th>
            
        </tr>
        @endforeach
    </tbody>
</table>

</body>
</html>